name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install
        git lfs pull
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Match CI error
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install onnx onnx-simplifier onnxruntime==1.12.0  # Replace with your local version
    - name: Verify Model File
      run: |
        ls -lh app/model/remx_model_1.0.0.onnx
        python -c "import onnx; model = onnx.load('app/model/remx_model_1.0.0.onnx'); onnx.checker.check_model(model); print('Model is valid')"
    - name: Check ONNX Runtime version
      run: |
        python -c "import onnxruntime; print(onnxruntime.__version__)"
    - name: Check ONNX Model Opset Version
      run: |
        python -c "import onnx; model = onnx.load('app/model/remx_model_1.0.0.onnx'); print(f'Model opset version: {model.opset_import[0].version}')"
    - name: Test Model Loading
      run: |
        python -c "import onnxruntime as ort; sess = ort.InferenceSession('app/model/remx_model_1.0.0.onnx'); print('Model loaded successfully')"
    - name: Simplify ONNX Model
      run: |
        python -c "import onnx; from onnxsim import simplify; model = onnx.load('app/model/remx_model_1.0.0.onnx'); simplified_model, check = simplify(model); onnx.save(simplified_model, 'app/model/remx_model_1.0.0_simplified.onnx'); print('Model simplified:', check)"
    - name: Validate ONNX Model
      run: |
        python validate_model.py
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
   